name: freelance
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  auto_route: ^9.2.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.2
  flutter_masked_text2: ^0.9.1
  flutter_otp_text_field: ^1.2.0
  iconify_flutter: ^0.0.7
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  image_picker: ^1.1.2
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  talker: ^4.4.7
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  talker_riverpod_logger: ^4.5.1
  flutter_svg: ^2.0.16
  cloud_firestore: ^5.6.2
  get_it: ^8.0.3
  get: ^4.6.6
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  auto_route_generator: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/.env

flutter_native_splash:
  color: "#FFD731"
  image: assets/images/splash.png
  android: true
  ios: true
