// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbXg4L3nohkp7cPSR8YheWElFt9uyUHFE',
    appId: '1:845076941333:web:f2ce2051690e03564e5c1c',
    messagingSenderId: '845076941333',
    projectId: 'freelance-f82f0',
    authDomain: 'freelance-f82f0.firebaseapp.com',
    storageBucket: 'freelance-f82f0.firebasestorage.app',
    measurementId: 'G-67NWG6MEYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQCE8Kh-2dgIknlourJeq1LeZsowshJY',
    appId: '1:845076941333:android:441fe0d0679c2a0f4e5c1c',
    messagingSenderId: '845076941333',
    projectId: 'freelance-f82f0',
    storageBucket: 'freelance-f82f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABg1SeOn-4UFoR7zsQy8xQEvOwkflUZeg',
    appId: '1:845076941333:ios:73d14b6c63ef17564e5c1c',
    messagingSenderId: '845076941333',
    projectId: 'freelance-f82f0',
    storageBucket: 'freelance-f82f0.firebasestorage.app',
    iosBundleId: 'com.freelance.dev',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABg1SeOn-4UFoR7zsQy8xQEvOwkflUZeg',
    appId: '1:845076941333:ios:73d14b6c63ef17564e5c1c',
    messagingSenderId: '845076941333',
    projectId: 'freelance-f82f0',
    storageBucket: 'freelance-f82f0.firebasestorage.app',
    iosBundleId: 'com.freelance.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbXg4L3nohkp7cPSR8YheWElFt9uyUHFE',
    appId: '1:845076941333:web:d79512e7caa437b74e5c1c',
    messagingSenderId: '845076941333',
    projectId: 'freelance-f82f0',
    authDomain: 'freelance-f82f0.firebaseapp.com',
    storageBucket: 'freelance-f82f0.firebasestorage.app',
    measurementId: 'G-8Y25ZLRVL0',
  );
}
